apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devsecops
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  clusterIP: None # Allows direct stable DNS for StatefulSet (headless service)
